package gui;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.net.ConnectException;
import java.net.Socket;
import java.net.UnknownHostException;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
/**
 *
 * @author Yogesh Dabas
 */
public class GUIWelcome extends javax.swing.JFrame {

    Banner banner1;
    String banner1Msg="Welcome to Run-On-Cloud GUI!!";
    Banner banner2;
    String banner2Msg="Developed by: Yogesh, Summer Intern 2015 at C-DOT, New Delhi";

    public GUIWelcome() {
        super("Run-On-Cloud GUI");
        
        File f=new File(".");
        System.out.println(f);
        Image img = Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("CDOT_logo.gif"));
        this.setIconImage(img);

        setSize(800, 550);
        initComponents();

        banner1 = new Banner(bannerLabel);
        banner1.setBanner(banner1Msg);
        Thread bannerThread = new Thread(banner1);
        bannerThread.start();
        
        banner2 = new Banner(bannerLabel1);
        banner2.setBanner(banner2Msg);
        Thread bannerThread2 = new Thread(banner2);
        bannerThread2.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ipTextField = new javax.swing.JTextField();
        portTextField = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        guiID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bannerLabel1 = new javax.swing.JLabel();
        bannerLabel = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 255)));

        jLabel2.setText("Enter your GUI ID");

        jLabel4.setText("Enter the Port Number");

        ipTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipTextFieldActionPerformed(evt);
            }
        });

        submit.setText("Connect");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel5.setText("Enter the Server IP Address");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ipTextField)
                            .addComponent(portTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(guiID)))
                    .addComponent(submit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guiID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submit)
                .addGap(16, 16, 16))
        );

        bannerLabel1.setBackground(new java.awt.Color(255, 255, 165));
        bannerLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bannerLabel1.setForeground(new java.awt.Color(0, 0, 204));
        bannerLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bannerLabel1.setOpaque(true);

        bannerLabel.setBackground(new java.awt.Color(255, 255, 165));
        bannerLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bannerLabel.setForeground(new java.awt.Color(0, 0, 204));
        bannerLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bannerLabel.setOpaque(true);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clouds.jpg"))); // NOI18N
        image.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bannerLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bannerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 802, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(527, 527, 527)
                .addComponent(bannerLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(bannerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

        try {

            String ip = ipTextField.getText();
            int port = Integer.parseInt(portTextField.getText());
            submit.setText("Connecting");
            String clientID = guiID.getText();
            if (!clientID.startsWith("GUI")) {
                JOptionPane.showMessageDialog(rootPane, "Please Enter a valid GUI ID!!\nGUI ID must start with GUI\n Example: GUI_1", "ERROR", ERROR_MESSAGE);
                submit.setText("Connect");
                guiID.setText("");
                ipTextField.setText("");
                portTextField.setText("");
            } else {
                Socket s = new Socket(ip, port);
                GUI g = new GUI(s, ip, port, clientID);
                JOptionPane.showMessageDialog(rootPane, "Connection Established!!", "Connected", INFORMATION_MESSAGE);
                dispose();

                g.setVisible(true);

                Thread t1 = new Thread(g, "tasklistThread");
                t1.setPriority(10);
                t1.start();

                Thread t2 = new Thread(g, "statisticsThread");
                t2.start();

                Thread t3 = new Thread(g, "newClientCountThread");
                t3.start();

                Thread t4 = new Thread(g, "disconnectedClientCountThread");
                t4.start();

                Thread t5 = new Thread(g, "programLoadingThread");
                t5.start();

                Thread t6 = new Thread(g, "ProgramExecutionThread");
                t6.start();

                Thread t7 = new Thread(g, "programFeedbackThread");
                t7.start();
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid Port Entered!!", "ERROR", ERROR_MESSAGE);
            submit.setText("Connect");
            guiID.setText("");
            ipTextField.setText("");
            portTextField.setText("");
        } catch (UnknownHostException e) {
            JOptionPane.showMessageDialog(rootPane, "Unknown Host Entered!!", "ERROR", ERROR_MESSAGE);
            submit.setText("Connect");
            guiID.setText("");
            ipTextField.setText("");
            portTextField.setText("");
        } catch (ConnectException e) {
            JOptionPane.showMessageDialog(rootPane, "Connection not established!!\nServer may be down or currently unavailable.", "ERROR", ERROR_MESSAGE);
            submit.setText("Connect");
            guiID.setText("");
            ipTextField.setText("");
            portTextField.setText("");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(rootPane, "OOPS Something went wrong\n Error: " + e.getMessage(), "ERROR", ERROR_MESSAGE);
        }


    }//GEN-LAST:event_submitActionPerformed

    private void ipTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIWelcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bannerLabel;
    private javax.swing.JLabel bannerLabel1;
    private javax.swing.JTextField guiID;
    private javax.swing.JLabel image;
    private javax.swing.JTextField ipTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField portTextField;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
